name: API Triggered Python Run

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: false
        default: '10'
      number2:
        description: 'Second number'
        required: false
        default: '20'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python
        run: python sum.py
        env:
          NUMBER1: ${{ github.event.inputs.number1 }}
          NUMBER2: ${{ github.event.inputs.number2 }}
